server:
  port: ${DISCOVERY_PORT:8761}

spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: ${DISCOVERY_HOST:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
