server:
  port: ${DISCOVERY_PORT:8761}

spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: ${DISCOVERY_HOST:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Exposes everything (health, metrics, beans, env, mappings)
  endpoint:
    health:
      show-details: always # Crucial: This shows you the exact status of MySQL and RabbitMQ!
  info:
    env:
      enabled: true # Allows you to pass custom app info
